### ISSUE TITLE
Not able to handle warning SizeAndTimeBasedFNATP

### ISSUE THREAD

**Issue by skabashnyuk** [tomcat-slf4j-logback/tomcat-slf4j-logback#144]
I have this warning after applying resources from tomcat-juli-8.5.11-slf4j-1.7.22-logback-1.1.8.zip to pure tomcat 8.5 
```
21:16:53,452 |-INFO in org.apache.juli.logging.ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7006c658 - The date pattern is 'yyyyMMdd' from file name pattern '/Users/sj/Downloads/tomcat85/apache-tomcat-8.5.11/logs/archive/catalina-%d{yyyyMMdd}-%i.log.zip'.
21:16:53,452 |-INFO in org.apache.juli.logging.ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7006c658 - Roll-over at midnight.
21:16:53,457 |-INFO in org.apache.juli.logging.ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7006c658 - Setting initial period to Sun Feb 26 21:16:53 EET 2017
21:16:53,458 |-WARN in org.apache.juli.logging.ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7006c658 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
```

**Comment by hazendaz** [comment]
Bug in logbook.  All we do is wrap slf4j/logback.  It's always best to check their first.  Issue is gone off our master as logback fixed the issue.  However I'm holding on release until final tomcat 6 is released.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by skabashnyuk** [comment]
I've got fixed this issue with 
+        <logback.version>1.2.1</logback.version>
+        <slf4j.version>1.7.24</slf4j.version>

but I got new
```
2017-02-26 22:35:16,811[ost-startStop-1]  [ERROR] [o.a.c.startup.ContextConfig 1624]    - Failed to detect ServletContainerInitializers for context with name [/docs]
java.io.IOException: java.lang.ClassNotFoundException: ch.qos.logback.classic.servlet.LogbackServletContainerInitializer
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:192)
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:159)
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1622)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1135)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.servlet.LogbackServletContainerInitializer
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:188)
	... 18 common frames omitted
```
I think it's because of this listener.
https://github.com/qos-ch/logback/commit/5688c15b1a97878ba7360e2a2f1c850d60ba6960
Any suggestion in which way should I go?

**Comment by skabashnyuk** [comment]
Looks like combination of 
+        <logback.version>1.1.9</logback.version>
+        <slf4j.version>1.7.24</slf4j.version>
is working.

**Comment by skabashnyuk** [comment]
@hazendaz would it be logical to create two issues?
- upgrade to  <logback.version>1.1.9</logback.version> and <slf4j.version>1.7.24</slf4j.version>
- study problems with logback > 1.1.9? 
wdyt?

**Comment by hazendaz** [comment]
I'll look shortly at this one.  Thanks.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by hazendaz** [comment]
@skabashnyuk no need to open new issue.  I will have it fixed shortly.  Logback 1.2.0 introduced  META-INF/services entry.  I haven't accounted for that in that revision and had already had the updates you mention locally but had not tested.  I was able to reproduce your error, found where the change was made and will adjust it to work with our setup shortly.

**Comment by skabashnyuk** [comment]
Great. Thanks.
