### ISSUE TITLE
Access logging is not working with default logback-access.xml and Tomcat 8.5.12

### ISSUE THREAD

**Issue by nike38rus** [tomcat-slf4j-logback/tomcat-slf4j-logback#153]
```
21:25:22,227 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - filename property not set. Assuming [conf/logback-access.xml]
21:25:22,228 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Found configuration file [/pub/site/app/conf/logback-access.xml] using property "catalina.base"
21:25:22,255 |-INFO in ch.qos.logback.access.joran.action.ConfigurationAction - debug attribute not set
21:25:22,261 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
21:25:22,264 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
21:25:22,288 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:25:22,289 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ACCESS-LOG]
21:25:22,303 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1427646530 - Archive files will be limited to [20 MB] each.
21:25:22,306 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1427646530 - Will use zip compression
21:25:22,308 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1427646530 - Will use the pattern /pub/site/app/logs/archive/localhost-access-%d{yyyyMMdd}-%i.log for the active file
21:25:22,310 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3270d194 - The date pattern is 'yyyyMMdd' from file name pattern '/pub/site/app/logs/archive/localhost-access-%d{yyyyMMdd}-%i.log.zip'.
21:25:22,310 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3270d194 - Roll-over at midnight.
21:25:22,314 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3270d194 - Setting initial period to Thu Mar 16 21:25:22 NOVT 2017
21:25:22,314 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3270d194 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
21:25:22,316 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1427646530 - Cleaning on start up
21:25:22,316 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@25:25 - RuntimeException in Action for tag [rollingPolicy] java.lang.UnsupportedOperationException
        at java.lang.UnsupportedOperationException
        at      at ch.qos.logback.access.tomcat.LogbackValve.getScheduledExecutorService(LogbackValve.java:452)
        at      at ch.qos.logback.core.rolling.helper.TimeBasedArchiveRemover.cleanAsynchronously(TimeBasedArchiveRemover.java:226)
        at      at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.start(TimeBasedRollingPolicy.java:112)
        at      at ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy.start(SizeAndTimeBasedRollingPolicy.java:30)
        at      at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:158)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:145)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:103)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at ch.qos.logback.access.tomcat.LogbackValve.configureAsResource(LogbackValve.java:219)
        at      at ch.qos.logback.access.tomcat.LogbackValve.startInternal(LogbackValve.java:149)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:170)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953)
        at      at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
        at      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:25:22,316 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS-LOG] - No TriggeringPolicy was set for the RollingFileAppender named ACCESS-LOG
21:25:22,316 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[ACCESS-LOG] - For more information, please visit http://logback.qos.ch/codes.html#rfa_no_tp
21:25:22,316 |-WARN in ch.qos.logback.core.joran.action.AppenderAction - The object at the of the stack is not the appender named [ACCESS-LOG] pushed earlier.
21:25:22,316 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an AppenderAttachable at the top of execution stack. Near [appender-ref] line 28
21:25:22,316 |-INFO in ch.qos.logback.access.joran.action.ConfigurationAction - End of configuration.
21:25:22,318 |-INFO in ch.qos.logback.access.joran.JoranConfigurator@4218d6a3 - Registering current configuration as safe fallback point
21:25:22,318 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Done configuring
```

Without `cleanHistoryOnStart` property logging works fine

**Comment by nike38rus** [comment]
I guess this bug is not related to this project but it can be workarounded by setting `cleanHistoryOnStart` property to false or removing it

**Comment by hazendaz** [comment]
I'm pretty sure that is fixed on master.  Sorry about that one.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by hazendaz** [comment]
@nike38rus Can you confirm build off master works for you?

**Comment by nike38rus** [comment]
@hazendaz Yes, it's working well. Thank you!
