### ISSUE TITLE
tomcat 8.5.24 cannot be launched

### ISSUE THREAD

**Issue by richwxd** [tomcat-slf4j-logback/tomcat-slf4j-logback#201]
The official tomcat-juli.jar has been modified, but this repository some classes are missing. See below:
Handler error
java.lang.ClassNotFoundException: org.apache.juli.AsyncFileHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:581)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:524)
	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:322)

**Comment by hazendaz** [comment]
Look in your conf directory.  You likely have tomcat original logging property file.  Delete that and your issue will go away.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing issue as this is not an issue but user configuraton not removing log4j properties which tomcat will look for and find and treat differently.  Please read the full readme doc.
